name: team_9_museum
description: Приложение для музеев с квестами, картой и геолокацией
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  google_mlkit_image_labeling: ^0.14.1
  image_picker: ^1.0.7
  google_mlkit_barcode_scanning: ^0.14.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/sled.png
